on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - bugfixes/ci-fixes
env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  WIFI_SSID: ${{ secrets.WIFI_SSID }}
  WIFI_PASS: ${{ secrets.WIFI_PASS }}

name: bloat

jobs:
  cargo_bloat:
    runs-on: xtensa-latest
    steps:
      - uses: actions/checkout@master
      - name: Run cargo bloat
        uses: izzyhub/cargo-bloat-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          bloat_args: --symbols-section .flash.text
