on:
  pull_request:
  push:
    branches:
      - main

name: Check and Lint

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  WIFI_SSID: ${{ secrets.WIFI_SSID }}
  WIFI_PASS: ${{ secrets.WIFI_PASS }}

jobs:
  check:
    name: Check
    runs-on: xtensa-latest
    steps:
      - uses: actions/checkout@v2
        with:
          default: true
          version: "latest"
          ldproxy: true
          #override: true
      - run: cargo check

  fmt:
    name: Rustfmt
    runs-on: xtensa-latest
    steps:
      - uses: actions/checkout@v2
        with:
          default: true
          version: "1.79.0.0"
          ldproxy: true
          override: true
      #- run: rustup component add rustfmt
      - run: cargo fmt --all --check

  clippy:
    name: Clippy
    runs-on: xtensa-latest
    steps:
      - uses: actions/checkout@v2
        with:
          default: true
          version: "1.79.0.0"
          ldproxy: true
      - run: cargo clippy
