on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - bugfixes/ci-fixes
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WIFI_SSID: ${{ secrets.WIFI_SSID }}
  WIFI_PASS: ${{ secrets.WIFI_PASS }}
  RUST_BACKTRACE: 1

name: bloat

jobs:
  cargo_bloat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust for Xtensa
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          version: "1.82.0"
          ldproxy: true
      - name: Run cargo bloat
        uses: orf/cargo-bloat-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          bloat_args: --symbols-section .flash.text
