on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - bugfixes/ci-fixes

name: bloat

jobs:
  cargo_bloat:
    runs-on: xtensa-latest
    steps:
      - uses: actions/checkout@master
      - name: Run cargo bloat
        uses: orf/cargo-bloat-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
