on:
  pull_request:
  push:
    branches:
      - main

name: Check and Lint

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: izzyhub/xtensa-toolchain@v1.5.5
        with:
          default: true
          version: "latest"
          ldproxy: true
          #override: true
      - run: cargo check

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: izzyhub/xtensa-toolchain@v1.5.5
        with:
          default: true
          version: "latest"
          ldproxy: true
          override: true
      - run: rustup component add rustfmt
      - run: cargo fmt --all --check

  clippy:
    name: Clippy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: izzyhub/xtensa-toolchain@v1.5.5
      - run: cargo clippy
