on:
  pull_request:
  push:
    branches:
      - main

name: Check and Lint

jobs:
  check:
    name: Check
    runs-on: ubuntu_xtensa
    steps:
      - uses: actions/checkout@v2
        with:
          default: true
          version: "latest"
          ldproxy: true
          #override: true
      - run: cargo check

  fmt:
    name: Rustfmt
    runs-on: ubuntu_xtensa
    steps:
      - uses: actions/checkout@v2
        with:
          default: true
          version: "1.79.0.0"
          ldproxy: true
          override: true
      - run: rustup component add rustfmt
      - run: cargo fmt --all --check

  clippy:
    name: Clippy
    runs-on: ubuntu_xtensa
    steps:
      - uses: actions/checkout@v2
        with:
          default: true
          version: "1.79.0.0"
          ldproxy: true
      - run: cargo clippy
