on:
  push:
    branches:
      - main

name: Release Packaging

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WIFI_SSID: ${{ secrets.WIFI_SSID }}
  WIFI_PASS: ${{ secrets.WIFI_PASS }}

jobs:
  release:
    name: Release Packaging
    env:
      PROJECT_NAME_UNDERSCORE: rust_ci_github_actions_workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          version: "1.79.0"
          ldproxy: true
      - name: Release Build
        run: cargo build --release
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: bbbot
          path: target/xtensa-esp32s3-espidf/release/bbbot
